Project2
MARS-JSU/Internship1400-backEnd-HamedGandomkar pull request #13
Opened 2021-08-16 19:22 UTC by hamedgk

2021-08-16 19:23 UTC, mhmdialireza approved these changes

2021-08-18 17:14 UTC, RAAvenger requested changes
<div dir="rtl">
سلام
حامد خسته نباشی
کلیات کدت خوبه ولی بعضی جاهای کدت انگار سر جای مناسبشون نیستن.

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Operation.php
> +    }
<div dir="rtl">
اینو ببر کلاس poly

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Operation.php
> +    }
<div dir="rtl">
به جای اینکه یک poly رو تو سازنده بگیری، سازنده رو خالی بذار.

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Operation.php
> +    }
<div dir="rtl">
کاربرد اینا چیه؟

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +    {
<div dir="rtl">
برای این کار متد toString رو رونویسی کن.

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +    }
<div dir="rtl">
این محاسبات رو ببر توی کلاس محاسبات متناسب با نوع ورودیشون

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    }
<div dir="rtl">
دستبندی کردن نام درستیه؟

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    }
<div dir="rtl">
کاربرد این کجاس؟

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    }
<div dir="rtl">
این مربوط به آنالایزر هست.

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    }
<div dir="rtl">
اینو بذار توی کلاس محاسباتیت.

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Operation.php
> +    }
<div dir="rtl">
اگر این عملیات داره توی کلاس Poly انجام میشه چرا اینجا هم تعریف شده؟

2021-08-18 17:14 UTC, RAAvenger commented on Project2/app/Utils/Preparation.php
> +    }
<div dir="rtl">
خروجی این میتونه Mono باشه.

2021-08-20 20:06 UTC, hamedgk commented on Project2/app/Operation.php
> +    }
اصلاح شد.

2021-08-20 20:06 UTC, hamedgk commented on Project2/app/Operation.php
> +    }
اصلاح شد.

2021-08-20 20:06 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +    {
اصلاح شد.

2021-08-20 20:16 UTC, hamedgk commented on Project2/app/Utils/Poly.php
> +    }
اصلاح شد.

2021-08-20 20:16 UTC, hamedgk commented on Project2/app/Utils/Poly.php
> +    }
اصلاح شد.

2021-08-20 20:17 UTC, hamedgk commented on Project2/app/Utils/Poly.php
> +    }
هنوز اسم گویایی پیدا نکردم اگر شما اسم بهتری سراغ داری خوشحال میشم پیشنهاد بدی

2021-08-20 20:24 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +    }
فکر نمیکنم روش مناسبی باشه! جدا از پیچیدگیش، بدنه کلاس محاسبات و پلی کلی بزرگ میشه. لطفا بیشتر توضیح بدین اگر بد متوجه شدم

2021-08-20 20:37 UTC, mhmdialireza requested changes

2021-08-20 20:37 UTC, mhmdialireza commented on Project2/app/Utils/Mono.php
> +        return "";
اینجوری خواناتره
if ($this->power == -1) {
	return "";
}
if ($this->power == 1) {
	if ($this->coffecent > 0) {
		return "+$this->coffecent" . "x";
	} else {
		return "$this->coffecent" . "x";
	}
} elseif ($this->power == 0) {
	if ($this->coffecent > 0) {
		return "+$this->coffecent";
	} else {
		return "$this->coffecent";
	}
} else {
	if ($this->coffecent > 0) {
		return "+$this->coffecent" . "x^" . "$this->power";
	} else {
		return "$this->coffecent" . "x^" . "$this->power";
	}
}

2021-08-21 11:05 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +    }
<div dir="rtl">
ببین شما یک کلاس محاسباتی داری که وظیفه انجام محاسبات بهش داده شده. حالا یک تعداد محاسبات داری که خارج از این کلاس انجام میشن و این غلطه.

برای جلوگیری از بزرگ شدن کلاس محاسباتیت میتونی بیای و در کنار کلاسی که محاسبات روی چند جمله‌ای ها رو پیاده سازی کرده یک کلاس صرفا برای محاسبات روی تک جمله‌ای ها داشته باشی.

2021-08-21 11:05 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    }
<div dir="rtl">
Cleanup

2021-08-21 11:31 UTC, RAAvenger reviewed
هنوز کدت جای بهبود داره.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Operation.php
> +        foreach($firstPoly->getMonos() as &$aMono){
<div dir="rtl">
دلیلی داره که اینجا از call By Reference استفاده میکنی؟

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +    private $power;
<div dir="rtl">
بد نیست اگر عادت کنی تا جای ممکن تایپ متغییرها رو تعیین کنی.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +        if ($this->power != -1) {
<div dir="rtl">
به جای فقط منفی یک میتونی بذاری کل اعداد منفی که درست‌تر باشه.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +                }
<div dir="rtl">
حالتی که ضریب صفر باشه رو کلا نادیده گرفتی.

بعد هم اینکه میتونی قدم به قدم رشته رو تولید کنی به جای اینکه همه رشته رو یکجا تولید کنی.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Mono.php
> +        return "";
<div dir="rtl">
خیلی تفاوتی نمیکنه.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +        $this->categorize();
<div dir="rtl">
چرا هی این رو صدا میزنی؟

استفاده از این متد رو به کاربر بسپار، شاید یک وقتی نخواد چند جمله‌ای حتما مرتب بشه.

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Preparation.php
> +        return $this->arrayOfMonos ?? new \Exception("uninitiated instance!");
<div dir="rtl">
اینجا جای throw کردن exception داری برش میگردونی، این تیکه رو با if(){throw}else{return} بازنویسی کن

2021-08-21 11:31 UTC, RAAvenger commented on Project2/app/Utils/Preparation.php
> +        }
<div dir="rtl">
اینجا چرا این متغییرها رو به عنوان attributeهای کلاس تعریف کردی؟

2021-08-21 11:32 UTC, mhmdialireza commented on Project2/app/Utils/Mono.php
> +        return "";
بخاطر این گفتم که وارد ۳ تا ایف نشه همزمان

2021-08-22 18:25 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +                }
حالت صفر پوشش داده شد

2021-08-22 18:25 UTC, hamedgk commented on Project2/app/Utils/Poly.php
> +        $this->categorize();
اصلاح شد.

2021-08-22 18:25 UTC, hamedgk commented on Project2/app/Utils/Preparation.php
> +        return $this->arrayOfMonos ?? new \Exception("uninitiated instance!");
اصلاح شد.

2021-08-22 18:26 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +        if ($this->power != -1) {
اصلاح شد.

2021-08-22 18:28 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +    private $power;
اصلاح شد.

2021-08-22 18:36 UTC, hamedgk commented on Project2/app/Operation.php
> +        foreach($firstPoly->getMonos() as &$aMono){
میذارم که سرعت بیشتر بشه. مگر اینکه بخوام کپی اطلاعات رو تغییر بدم.

2021-08-22 18:41 UTC, hamedgk commented on Project2/app/Utils/Preparation.php
> +        }
متوجه منظورتون نمیشم. اینجا در واقع دارم علامتی که اول کار جدا کردم رو دوباره میچسبونم

2021-08-22 18:42 UTC, hamedgk commented on Project2/app/Utils/Mono.php
> +    }
اصلاح شد.

2021-08-22 18:42 UTC, hamedgk commented on Project2/app/Utils/Poly.php
> +    }
اصلاح شد.

2021-08-23 13:39 UTC, RAAvenger commented on Project2/app/Utils/Preparation.php
> +        }
<div dir=rtl>
منظورم اینه که متغییرها رو به جای اینکه در سطح کلاس تعریف کنی میتونی در سطح توابع تعریف کنی، حالا نیاز نیست الان روی این کار کنی، ولی توی فازای بعدی به این دقت کن.

2021-08-23 13:43 UTC, RAAvenger approved these changes
خسته نباشی

2021-08-23 13:43 UTC, RAAvenger commented on Project2/app/Utils/Poly.php
> +    {
__toString()

2021-08-23 17:34 UTC, merged